repository:
  name: sun50i-a64-gpadc-iio
  description: Out-of-tree Linux kernel module for thermal sensor on Allwinner A64 SoC
  topics: linux-kernel-module
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: develop
  allow_merge_commit: true
  allow_squash_merge: false
  allow_rebase_merge: false

collaborators: []

teams:
- name: central
  permission: push

branches:
- name: master
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: false
      require_code_owner_reviews: true
      dismissal_restrictions:
        users: []
        teams: []
    required_status_checks:
      strict: true
      contexts: []
    enforce_admins: true
    restrictions:
      users: []
      teams: []
